### PR TITLE
Add the Json library to the dependencies

### PR DESCRIPTION
**Pull request by ageron**
The Json library is needed by the upcoming rest-api exercise

### CODE REVIEW

**Comment by IsaacG** [comment]
Is there any way to confirm this doesn't significantly impact the image size?

**Review by IsaacG — APPROVED** [review]

**Comment by ageron** [comment]
Thanks for your review, @IsaacG 
Regarding the size, these packages are pretty small, so it shouldn't be an issue.
What would be a problematic size? What problems could it cause?
We could add a GitHub Action to check the size?

**Comment by IsaacG** [comment]
> Regarding the size, these packages are pretty small, so it shouldn't be an issue.
> What would be a problematic size? What problems could it cause?

If it's small, it should be fine. I have no idea what size they are. One of Exercism's larger costs is image storage.

**Comment by ageron** [comment]
Here are the sizes:

| Package            | Download | Decompressed |
|--------------------|----------|--------------|
| Roc                | 33.9M    | 95.5M        |
| basic-cli platform |  8.2M    | 45.3M        |
| Unicode package    |  0.1M    |  1.2M        |
| Json package       |  0.0M    |  0.1M        |
| Isodate package    |  0.0M    |  0.1M        |

Literally 99% of the size is the absolute minimum we need to run Roc: the `roc` compiler + the basic-cli platform.
I'll chat with the Roc team to see if we can shrink that down somehow.

At least these numbers show that we can add a few more packages without having any significant impact.

**Comment by IsaacG** [comment]
Those sizes definitely sounds like they are completely fine!! Thank you for checking.

**Comment by ageron** [comment]
We're currently using the Ubuntu 24.04 base image, which looks like it's about 80M.

We're also using:
* `wget`
* `jq`
* `libc-dev`
* `binutils`

I'm not sure how to tell how big these packages and their dependencies are.

It might help to switch to Alpine as our base image, but right now Roc does not yet support it. It's work in progress, so when that's ready, we can switch and hopefully shrink the image a bit.

**Comment by IsaacG** [comment]
If you can switch to Alpine, that would be nice. But don't worry about it too much. Maybe tracks use Ubuntu images as they tend to be easier to work with.

**Pull request merged**
